[build-system]
requires = ["setuptools", "Cython"]
build-backend = "setuptools.build_meta"

[project]
name = "reazonspeech-nemo-asr"
version = "2.0.1"
dependencies = [
    "numpy",
    "librosa",
    "soundfile",
    "torch",
    "nemo_toolkit[asr]",
]

[tool.setuptools.package-dir]
"reazonspeech.nemo.asr" = "src"

[project.scripts]
reazonspeech-nemo-asr = "reazonspeech.nemo.asr.cli:main"
